import { Metadata } from 'next';
import React from 'react'


export const metadata: Metadata = {
    title: "region",
    description: "Generated by create next app",
  };

export default function layout({
    children,
  }: {
    children: React.ReactNode;
  }) {
  return (
    <div>{children}</div>
  )
}
